### HOLT-WINTERS FORECASTING

# file generated by pre-processing_TS.R
smart_meters <- readRDS(file = "smart_meters.R")


## time series analysis for the whole yearly energy consumption

# Aggregating by week without falling into the trap of counting the same
# week twice because it gets cut by the end of the year you know what I mean


# create day of the year column
smart_meters$day_of_year <-strftime(smart_meters$date.time, format = "%j")

# group by day of the year and year
smart_meters_ts_df <- smart_meters %>% 
  select(year, day_of_year, kw_per_min) %>% 
  group_by(year, day_of_year) %>%
  summarise(mean_kwmin = mean(kw_per_min))


# create unique id for every week
my_month <- rep(1:1000, each = 31, length.out = nrow(smart_meters_ts_df))
smart_meters_ts_df$my_month <- my_month

# group by week id in order not to cut weeks at the end of the year
smart_meters_ts_df <- smart_meters_ts_df %>% 
  group_by(my_month) %>% 
  summarise(mean_kwmin = mean(mean_kwmin))


## creating the time series
smart_meters_ts <-
  ts(smart_meters_ts_df$mean_kwmin,
     frequency = 12,
     start = c(2007, 1),
     end = c(2009, 12))


plot.ts(smart_meters_ts)



## simple moving average for kW per minute

SMA_smart_meters_ts <- SMA(smart_meters_ts, n = 2)

plot.ts(SMA_smart_meters_ts)



## decomposing the weekly time series for kW per minute

dec_smart_meters_ts <- decompose(smart_meters_ts)

plot(dec_smart_meters_ts)



## forecasting energy consumption using Holt Winters...

forecast_energycons <- HoltWinters(smart_meters_ts, 
                                   beta = NULL,
                                   gamma = NULL,
                                   l.start = 24.74)


forecast_energycons
plot(forecast_energycons)


## errors

forecast_energycons$SSE

sqrt(forecast_energycons$SSE/52)

forecast_energycons$fitted


## ... for 52 weeks more (so for one year more, which is 2010)

forecast_energycons_HW <- forecast(forecast_energycons,
                                   h = 24,
                                   level = c(80,90))


forecast_energycons_HW

plot(forecast_energycons_HW, start(2010))
plot(forecast_energycons_HW)


## ACF of residuals of Holt Winters forecast

acf(forecast_energycons_HW$residuals, 
    lag.max = 10,
    na.action = na.pass)

plot(forecast_energycons_HW$residuals)


## .. and the partial ACF likewise

pacf(forecast_energycons_HW$residuals, 
     lag.max = 10,
     na.action = na.pass)

pacf(forecast_energycons_HW$residuals, 
     lag.max = 10,
     na.action = na.pass,
     plot = FALSE)

plot.ts(forecast_energycons_HW$residuals)  # same as above or ??


## Ljung Box Test

Box.test(forecast_energycons_HW$residuals, 
         lag = 10, 
         type = "Ljung-Box")

