
## Forecasting using the TS Studio package


# file generated by pre-processing_TS.R
smart_meters <- readRDS(file = "smart_meters.R")


## time series analysis for the whole yearly energy consumption

# Aggregating by week without falling into the trap of counting the same
# week twice because it gets cut by the end of the year you know what I mean


# create day of the year column
smart_meters$day_of_year <-strftime(smart_meters$date.time, format = "%j")

# group by day of the year and year
smart_meters_ts_df <- smart_meters %>% 
  select(year, day_of_year, kw_per_min) %>% 
  group_by(year, day_of_year) %>%
  summarise(mean_kwmin = mean(kw_per_min))


# create unique id for every month
my_month <- rep(1:1000, each = 31, length.out = nrow(smart_meters_ts_df))
smart_meters_ts_df$my_month <- my_month

# group by month id   ((in order not to cut weeks at the end of the year))
smart_meters_ts_df <- smart_meters_ts_df %>% 
  group_by(my_month) %>% 
  summarise(mean_kwmin = mean(mean_kwmin))


## creating the time series
smart_meters_ts <-
  ts(smart_meters_ts_df$mean_kwmin,
     frequency = 12,
     start = c(2007, 1),
     end = c(2009, 12))


plot.ts(smart_meters_ts)


## TSstudio package

ts_info(smart_meters_ts)

ts_plot(smart_meters_ts,
        title = "Yearly energy consumption from 2007 to 2009",
        Ytitle = "KW per minute",
        Xtitle = "Timeline", 
        slider = TRUE)


# Decomposition methods

ts_decompose(smart_meters_ts)

decomp = stl(smart_meters_ts, s.window = "periodic")
seasadj(decomp)
decomp

## Visualizing the time series data

ts_seasonal(smart_meters_ts)
ts_seasonal(smart_meters_ts-decompose(smart_meters_ts)$trend,
            type = "box")

ts_heatmap(smart_meters_ts)


## ACF and lags

ts_acf(smart_meters_ts, lag.max = 12)

ts_lags(smart_meters_ts, lags = c(1,5,8,12))


## Augmented Dickey-Fuller test

adf.test(smart_meters_ts, alternative = "stationary")



### ARIMA MODEL

## Fitting the ARIMA Model

arima_fit <- arima(train, order = c(1,1,10))

arima_fit
plot(arima_fit)

tsdisplay(residuals(arima_fit), lag.max = 12)


## forecasting with the fitted ARIMA Model

arima_forecast <- forecast(arima_fit, h = 12)

arima_forecast
plot(arima_forecast, start(2010))


## splitting the data into test and trainig

smart_meters_split <- ts_split(smart_meters_ts, 
                               sample.out = 6)

train <- smart_meters_split$train
test <- smart_meters_split$test

ts_info(train)
ts_info(test)


## testing accuracy of the ARIMA Model

accuracy(arima_forecast, test)

test_forecast(forecast.obj = arima_forecast, 
              actual = smart_meters_ts, 
              test = test) %>% 
  layout(legend = list(x = 36, y = 42))   ## ?????


